version: '3.8'

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        environment:
            - ENVIRONMENT=development
            - DEBUG=1
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: 'postgres:15'
        expose:
            - "5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    

volumes:
    postgres_data: