# Generated by Django 4.2.7 on 2023-12-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='smallDescription',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='type',
            field=models.CharField(choices=[('category', 'Category'), ('product', 'Product'), ('banner', 'Prdouct - Banner'), ('banner2', 'Category - Banner'), ('no url image', 'no url image')], max_length=15),
        ),
    ]
